name: CI Pipeline

# Trigger the workflow on pushes and pull requests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18]  # Specify the Node.js versions to test against

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to v3

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Updated to v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --verbose  # Adds verbosity for better debugging

      # Optional: Archive test results, if configured to store artifacts in test-results/ directory
      - name: Archive test results
        if: failure()
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: test-results
          path: test-results/  # Ensure Jest or test framework outputs here, or remove if unused

          